use std::fmt::Write as _;

use parc::contract::{ExactInteger, MacroValue};

use crate::{
    RustEnum, RustFunction, RustItem, RustMacro, RustRecord, RustRecordKind, RustType,
    RustTypeKind, RustVariable, ValidatedRustProjection,
};

pub(crate) fn render_projection(projection: &ValidatedRustProjection) -> String {
    let mut output = String::from(
        "// @generated by GERC from checked PARC source and LINC evidence.\n\
         // Do not edit by hand.\n\n\
         #![no_std]\n\
         #![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]\n\n",
    );

    for source_macro in projection.macros().iter().filter(|item| item.emitted()) {
        render_macro(&mut output, source_macro);
    }
    for item in projection.items() {
        match item {
            RustItem::Function(item) => render_function(&mut output, item),
            RustItem::Record(item) => render_record(&mut output, item),
            RustItem::Enum(item) => render_enum(&mut output, item),
            RustItem::TypeAlias(item) => {
                writeln!(
                    output,
                    "pub type {} = {};\n",
                    item.rust_name().as_str(),
                    render_type(item.target())
                )
                .expect("writing into a String cannot fail");
            }
            RustItem::Variable(item) => render_variable(&mut output, item),
        }
    }
    output
}

fn render_macro(output: &mut String, source_macro: &RustMacro) {
    let Some(value) = source_macro.value() else {
        return;
    };
    match value {
        MacroValue::Integer { value } => {
            let (value, ty) = render_exact_integer(*value);
            writeln!(
                output,
                "pub const {}: {ty} = {value};\n",
                source_macro.rust_name().as_str()
            )
            .expect("writing into a String cannot fail");
        }
        MacroValue::String { value } => {
            writeln!(
                output,
                "pub const {}: &str = {:?};\n",
                source_macro.rust_name().as_str(),
                value
            )
            .expect("writing into a String cannot fail");
        }
        MacroValue::Tokens { .. } => {}
    }
}

fn render_function(output: &mut String, function: &RustFunction) {
    writeln!(output, "unsafe extern {:?} {{", function.abi().spelling())
        .expect("writing into a String cannot fail");
    writeln!(output, "    #[link_name = {:?}]", function.link_name())
        .expect("writing into a String cannot fail");
    write!(output, "    pub fn {}(", function.rust_name().as_str())
        .expect("writing into a String cannot fail");
    for (index, parameter) in function.parameters().iter().enumerate() {
        if index != 0 {
            output.push_str(", ");
        }
        write!(
            output,
            "{}: {}",
            parameter.rust_name().as_str(),
            render_type(parameter.ty())
        )
        .expect("writing into a String cannot fail");
    }
    if function.variadic() {
        if !function.parameters().is_empty() {
            output.push_str(", ");
        }
        output.push_str("...");
    }
    output.push(')');
    if !matches!(function.return_type().kind(), RustTypeKind::Void) {
        write!(output, " -> {}", render_type(function.return_type()))
            .expect("writing into a String cannot fail");
    }
    output.push_str(";\n}\n\n");
}

fn render_record(output: &mut String, record: &RustRecord) {
    match record.kind() {
        RustRecordKind::Opaque => {
            writeln!(
                output,
                "#[repr(C)]\npub struct {} {{\n    _private: [u8; 0],\n}}\n",
                record.rust_name().as_str()
            )
            .expect("writing into a String cannot fail");
        }
        RustRecordKind::Struct => {
            let alignment_bytes = record
                .alignment_bits()
                .expect("validated concrete record has alignment")
                / 8;
            output.push_str("#[repr(C)]\n");
            writeln!(output, "pub struct {} {{", record.rust_name().as_str())
                .expect("writing into a String cannot fail");
            for field in record.fields() {
                writeln!(
                    output,
                    "    pub {}: {},",
                    field.rust_name().as_str(),
                    render_type(field.ty())
                )
                .expect("writing into a String cannot fail");
            }
            output.push_str("}\n");
            let size_bits = record
                .size_bits()
                .expect("validated concrete record has size");
            writeln!(
                output,
                "const _: () = assert!(core::mem::size_of::<{}>() == {});",
                record.rust_name().as_str(),
                size_bits / 8
            )
            .expect("writing into a String cannot fail");
            for field in record.fields() {
                writeln!(
                    output,
                    "const _: () = assert!(core::mem::offset_of!({}, {}) == {});",
                    record.rust_name().as_str(),
                    field.rust_name().as_str(),
                    field.offset_bits() / 8
                )
                .expect("writing into a String cannot fail");
            }
            writeln!(
                output,
                "const _: () = assert!(core::mem::align_of::<{}>() == {alignment_bytes});\n",
                record.rust_name().as_str()
            )
            .expect("writing into a String cannot fail");
        }
    }
}

fn render_enum(output: &mut String, enumeration: &RustEnum) {
    writeln!(
        output,
        "#[repr(transparent)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct {}(pub {});",
        enumeration.rust_name().as_str(),
        enumeration.storage().spelling()
    )
    .expect("writing into a String cannot fail");
    for variant in enumeration.variants() {
        let (value, _) = render_exact_integer(variant.value());
        writeln!(
            output,
            "pub const {}: {} = {}({value} as {});",
            variant.rust_name().as_str(),
            enumeration.rust_name().as_str(),
            enumeration.rust_name().as_str(),
            enumeration.storage().spelling()
        )
        .expect("writing into a String cannot fail");
    }
    writeln!(
        output,
        "const _: () = assert!(core::mem::size_of::<{}>() == {});",
        enumeration.rust_name().as_str(),
        enumeration.storage().size_bits() / 8
    )
    .expect("writing into a String cannot fail");
    writeln!(
        output,
        "const _: () = assert!(core::mem::align_of::<{}>() == {});",
        enumeration.rust_name().as_str(),
        enumeration.alignment_bits() / 8
    )
    .expect("writing into a String cannot fail");
    output.push('\n');
}

fn render_variable(output: &mut String, variable: &RustVariable) {
    output.push_str("unsafe extern \"C\" {\n");
    writeln!(output, "    #[link_name = {:?}]", variable.link_name())
        .expect("writing into a String cannot fail");
    let mutable = if variable.ty().qualifiers().is_const {
        ""
    } else {
        "mut "
    };
    writeln!(
        output,
        "    pub static {mutable}{}: {};",
        variable.rust_name().as_str(),
        render_type(variable.ty())
    )
    .expect("writing into a String cannot fail");
    output.push_str("}\n\n");
}

fn render_type(ty: &RustType) -> String {
    match ty.kind() {
        RustTypeKind::Void => "core::ffi::c_void".to_owned(),
        RustTypeKind::Scalar(scalar) => scalar.spelling().to_owned(),
        RustTypeKind::Pointer(pointee) => {
            let qualifier = if pointee.qualifiers().is_const {
                "const"
            } else {
                "mut"
            };
            format!("*{qualifier} {}", render_type(pointee))
        }
        RustTypeKind::FixedArray { element, elements } => {
            format!("[{}; {elements}]", render_type(element))
        }
        RustTypeKind::Named { rust_name, .. } => rust_name.as_str().to_owned(),
        RustTypeKind::FunctionPointer {
            abi,
            parameters,
            return_type,
            variadic,
        } => {
            let mut rendered = format!("Option<unsafe extern {:?} fn(", abi.spelling());
            for (index, parameter) in parameters.iter().enumerate() {
                if index != 0 {
                    rendered.push_str(", ");
                }
                rendered.push_str(&render_type(parameter));
            }
            if *variadic {
                if !parameters.is_empty() {
                    rendered.push_str(", ");
                }
                rendered.push_str("...");
            }
            rendered.push(')');
            if !matches!(return_type.kind(), RustTypeKind::Void) {
                write!(rendered, " -> {}", render_type(return_type))
                    .expect("writing into a String cannot fail");
            }
            rendered.push('>');
            rendered
        }
    }
}

fn render_exact_integer(value: ExactInteger) -> (String, &'static str) {
    match value {
        ExactInteger::Signed { value } => (value.to_string(), "i128"),
        ExactInteger::Unsigned { value } => (value.to_string(), "u128"),
    }
}

#[cfg(test)]
mod tests {
    use std::{fs, process::Command};

    use parc::contract::{Nullability, SupportStatus, TypeQualifiers};

    use crate::{RustAbi, RustScalar, RustType, RustTypeKind};

    use super::render_type;

    #[test]
    fn pointer_to_c_function_projects_as_nullable_function_pointer() {
        let scalar = || RustType {
            qualifiers: TypeQualifiers::NONE,
            nullability: Nullability::Unspecified,
            support: SupportStatus::Supported,
            kind: RustTypeKind::Scalar(RustScalar::I32),
        };
        let callback = RustType {
            qualifiers: TypeQualifiers::NONE,
            nullability: Nullability::Nullable,
            support: SupportStatus::Supported,
            kind: RustTypeKind::FunctionPointer {
                abi: RustAbi::C,
                parameters: vec![scalar()],
                return_type: Box::new(scalar()),
                variadic: false,
            },
        };
        let rendered = render_type(&callback);
        assert_eq!(rendered, "Option<unsafe extern \"C\" fn(i32) -> i32>");
        assert!(!rendered.contains("*mut"));

        let source = format!("#![no_std]\npub type callback = {rendered};\n");
        let directory =
            std::env::temp_dir().join(format!("gerc-function-pointer-{}", std::process::id()));
        fs::create_dir_all(&directory).expect("create compile-test directory");
        let input = directory.join("lib.rs");
        fs::write(&input, source).expect("write compile-test source");
        let rustc = std::env::var_os("RUSTC").unwrap_or_else(|| "rustc".into());
        let result = Command::new(rustc)
            .arg("--crate-name=function_pointer_projection")
            .arg("--crate-type=lib")
            .arg("--edition=2021")
            .arg("--emit=metadata")
            .arg("-o")
            .arg(directory.join("lib.rmeta"))
            .arg(&input)
            .output()
            .expect("run rustc");
        let _ = fs::remove_dir_all(&directory);
        assert!(
            result.status.success(),
            "function pointer projection did not compile:\n{}",
            String::from_utf8_lossy(&result.stderr)
        );
    }

    #[test]
    fn c_bool_uses_rust_bool_not_integer_abi() {
        let c_bool = RustType {
            qualifiers: TypeQualifiers::NONE,
            nullability: Nullability::Unspecified,
            support: SupportStatus::Supported,
            kind: RustTypeKind::Scalar(RustScalar::Bool),
        };
        assert_eq!(render_type(&c_bool), "bool");
    }
}
