//! Rust source code emission from the projection IR.
//!
//! Turns `RustProjection` items into deterministic Rust source text.

use crate::ir::*;
use std::collections::BTreeSet;

/// Emit a complete Rust source file from a projection.
pub fn emit_source(proj: &RustProjection) -> String {
    let mut out = String::new();
    out.push_str("// Generated by GERC — do not edit.\n");
    out.push_str("#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]\n\n");
    emit_projection_notes(&mut out, &proj.notes);

    // Collect extern "C" functions and statics
    let mut extern_fns = Vec::new();
    let mut extern_statics = Vec::new();
    let mut other_items = Vec::new();

    for item in &proj.items {
        match item {
            RustItem::Function(f) => extern_fns.push(f),
            RustItem::Static(s) => extern_statics.push(s),
            _ => other_items.push(item),
        }
    }

    // 7.3: Emit constants
    for item in &other_items {
        if let RustItem::Constant(c) = item {
            emit_constant(&mut out, c);
            out.push('\n');
        }
    }

    emit_missing_named_type_placeholders(&mut out, proj);

    // 7.7: Emit type aliases
    for item in &other_items {
        if let RustItem::TypeAlias(t) = item {
            emit_type_alias(&mut out, t);
            out.push('\n');
        }
    }

    // 7.6: Emit enums
    for item in &other_items {
        if let RustItem::Enum(e) = item {
            emit_enum(&mut out, e);
            out.push('\n');
        }
    }

    // 7.4 & 7.5: Emit structs and unions
    for item in &other_items {
        if let RustItem::Record(r) = item {
            emit_record(&mut out, r);
            out.push('\n');
        }
    }

    // 7.2 & 7.8: Emit extern "C" block
    if !extern_fns.is_empty() || !extern_statics.is_empty() {
        out.push_str("extern \"C\" {\n");
        for s in &extern_statics {
            emit_static_decl(&mut out, s);
        }
        for f in &extern_fns {
            emit_function_decl(&mut out, f);
        }
        out.push_str("}\n");
    }

    // Emit unsupported items as comments
    for item in &other_items {
        if let RustItem::Unsupported(u) = item {
            out.push_str(&format!(
                "// unsupported: {} — {}\n",
                u.name.as_deref().unwrap_or("<anonymous>"),
                u.reason
            ));
        }
    }

    out
}

fn emit_doc_comment(out: &mut String, doc: Option<&str>, indent: &str) {
    let Some(doc) = doc else {
        return;
    };

    for line in doc.lines() {
        out.push_str(indent);
        out.push_str("///");
        if !line.is_empty() {
            out.push(' ');
            out.push_str(line);
        }
        out.push('\n');
    }
}

fn emit_projection_notes(out: &mut String, notes: &[ProjectionNote]) {
    let mut emitted = false;

    for note in notes {
        if note.kind == NoteKind::Projected {
            continue;
        }

        if !emitted {
            out.push_str("// Projection notes:\n");
            emitted = true;
        }

        out.push_str("// ");
        out.push_str(note_kind_label(note.kind));
        if let Some(item_name) = note.item_name.as_deref() {
            out.push_str(" [");
            out.push_str(item_name);
            out.push(']');
        }
        out.push_str(": ");
        out.push_str(&note.message);
        out.push('\n');
    }

    if emitted {
        out.push('\n');
    }
}

fn note_kind_label(kind: NoteKind) -> &'static str {
    match kind {
        NoteKind::Projected => "projected",
        NoteKind::Unsupported => "unsupported",
        NoteKind::Partial => "partial",
        NoteKind::Provenance => "provenance",
    }
}

/// 7.2: Emit function declaration inside extern "C" block.
fn emit_function_decl(out: &mut String, f: &RustFunction) {
    emit_doc_comment(out, f.doc.as_deref(), "    ");
    out.push_str("    pub fn ");
    out.push_str(&escape_ident(&f.name));
    out.push('(');
    for (i, p) in f.parameters.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&escape_ident(&p.name));
        out.push_str(": ");
        out.push_str(&emit_type(&p.ty));
    }
    if f.variadic {
        if !f.parameters.is_empty() {
            out.push_str(", ");
        }
        out.push_str("...");
    }
    out.push(')');
    if !matches!(f.return_type, RustType::Void) {
        out.push_str(" -> ");
        out.push_str(&emit_type(&f.return_type));
    }
    out.push_str(";\n");
}

/// 7.3: Emit a Rust constant.
fn emit_constant(out: &mut String, c: &RustConstant) {
    emit_doc_comment(out, c.doc.as_deref(), "");
    out.push_str("pub const ");
    out.push_str(&escape_ident(&c.name));
    out.push_str(": ");
    out.push_str(&emit_type(&c.ty));
    out.push_str(" = ");
    out.push_str(&c.value);
    out.push_str(";\n");
}

/// 7.4 & 7.5: Emit struct or union.
fn emit_record(out: &mut String, r: &RustRecord) {
    emit_doc_comment(out, r.doc.as_deref(), "");
    if r.is_opaque {
        // Opaque type as an empty repr(C) struct
        out.push_str("#[repr(C)]\n");
        out.push_str("pub struct ");
        out.push_str(&r.name);
        out.push_str(" { _opaque: [u8; 0] }\n");
        return;
    }

    out.push_str("#[repr(C)]\n");
    match r.kind {
        RustRecordKind::Struct => out.push_str("pub struct "),
        RustRecordKind::Union => out.push_str("pub union "),
    }
    out.push_str(&r.name);
    out.push_str(" {\n");
    for field in &r.fields {
        out.push_str("    pub ");
        out.push_str(&escape_ident(&field.name));
        out.push_str(": ");
        out.push_str(&emit_type(&field.ty));
        out.push_str(",\n");
    }
    out.push_str("}\n");
}

/// 7.6: Emit enum with explicit representation.
fn emit_enum(out: &mut String, e: &RustEnum) {
    emit_doc_comment(out, e.doc.as_deref(), "");
    out.push_str(&format!("#[repr({})]\n", e.repr));
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum ");
    out.push_str(&e.name);
    out.push_str(" {\n");
    for v in &e.variants {
        out.push_str("    ");
        out.push_str(&escape_ident(&v.name));
        if let Some(val) = v.value {
            out.push_str(&format!(" = {}", val));
        }
        out.push_str(",\n");
    }
    out.push_str("}\n");
}

/// 7.7: Emit type alias.
fn emit_type_alias(out: &mut String, t: &RustTypeAlias) {
    emit_doc_comment(out, t.doc.as_deref(), "");
    out.push_str("pub type ");
    out.push_str(&t.name);
    out.push_str(" = ");
    out.push_str(&emit_type(&t.target));
    out.push_str(";\n");
}

/// 7.8: Emit static declaration inside extern "C" block.
fn emit_static_decl(out: &mut String, s: &RustStatic) {
    emit_doc_comment(out, s.doc.as_deref(), "    ");
    out.push_str("    pub static ");
    if s.mutable {
        out.push_str("mut ");
    }
    out.push_str(&escape_ident(&s.name));
    out.push_str(": ");
    out.push_str(&emit_type(&s.ty));
    out.push_str(";\n");
}

fn emit_missing_named_type_placeholders(out: &mut String, proj: &RustProjection) {
    let defined = collect_defined_type_names(proj);
    let referenced = collect_referenced_type_names(proj);
    let mut emitted_any = false;

    for name in referenced.difference(&defined) {
        if !is_placeholder_safe_name(name) {
            continue;
        }
        if !emitted_any {
            out.push_str("// Opaque placeholders for unresolved named C types\n");
            emitted_any = true;
        }
        out.push_str("#[repr(C)]\n");
        out.push_str("pub struct ");
        out.push_str(&escape_ident(name));
        out.push_str(" { _opaque: [u8; 0] }\n\n");
    }
}

fn collect_defined_type_names(proj: &RustProjection) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for item in &proj.items {
        match item {
            RustItem::Record(r) => {
                names.insert(r.name.clone());
            }
            RustItem::Enum(e) => {
                names.insert(e.name.clone());
            }
            RustItem::TypeAlias(t) => {
                names.insert(t.name.clone());
            }
            _ => {}
        }
    }
    names
}

fn collect_referenced_type_names(proj: &RustProjection) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for item in &proj.items {
        match item {
            RustItem::Function(f) => {
                collect_named_types(&f.return_type, &mut names);
                for p in &f.parameters {
                    collect_named_types(&p.ty, &mut names);
                }
            }
            RustItem::Record(r) => {
                for field in &r.fields {
                    collect_named_types(&field.ty, &mut names);
                }
            }
            RustItem::Enum(_) => {}
            RustItem::TypeAlias(t) => collect_named_types(&t.target, &mut names),
            RustItem::Constant(c) => collect_named_types(&c.ty, &mut names),
            RustItem::Static(s) => collect_named_types(&s.ty, &mut names),
            RustItem::Unsupported(_) => {}
        }
    }
    names
}

fn collect_named_types(ty: &RustType, names: &mut BTreeSet<String>) {
    match ty {
        RustType::Pointer { pointee, .. } => collect_named_types(pointee, names),
        RustType::Array { element, .. } => collect_named_types(element, names),
        RustType::FnPointer { params, ret, .. } => {
            collect_named_types(ret, names);
            for param in params {
                collect_named_types(param, names);
            }
        }
        RustType::Named(name) => {
            names.insert(name.clone());
        }
        _ => {}
    }
}

fn is_placeholder_safe_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn escape_ident(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
        "unsafe", "use", "where", "while", "async", "await", "dyn",
    ];

    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// Emit a Rust type as source text.
pub fn emit_type(ty: &RustType) -> String {
    match ty {
        RustType::Void => "()".into(),
        RustType::Bool => "bool".into(),
        RustType::CChar => "core::ffi::c_char".into(),
        RustType::CSChar => "core::ffi::c_schar".into(),
        RustType::CUChar => "core::ffi::c_uchar".into(),
        RustType::CShort => "core::ffi::c_short".into(),
        RustType::CUShort => "core::ffi::c_ushort".into(),
        RustType::CInt => "core::ffi::c_int".into(),
        RustType::CUInt => "core::ffi::c_uint".into(),
        RustType::CLong => "core::ffi::c_long".into(),
        RustType::CULong => "core::ffi::c_ulong".into(),
        RustType::CLongLong => "core::ffi::c_longlong".into(),
        RustType::CULongLong => "core::ffi::c_ulonglong".into(),
        RustType::F32 => "f32".into(),
        RustType::F64 => "f64".into(),
        RustType::Pointer { pointee, is_const } => {
            if *is_const {
                format!("*const {}", emit_type(pointee))
            } else {
                format!("*mut {}", emit_type(pointee))
            }
        }
        RustType::Array { element, len } => match len {
            Some(n) => format!("[{}; {}]", emit_type(element), n),
            None => format!("[{}; 0]", emit_type(element)),
        },
        RustType::FnPointer {
            params,
            ret,
            variadic,
        } => {
            let mut s = String::from("Option<unsafe extern \"C\" fn(");
            for (i, p) in params.iter().enumerate() {
                if i > 0 {
                    s.push_str(", ");
                }
                s.push_str(&emit_type(p));
            }
            if *variadic {
                if !params.is_empty() {
                    s.push_str(", ");
                }
                s.push_str("...");
            }
            s.push(')');
            if !matches!(**ret, RustType::Void) {
                s.push_str(" -> ");
                s.push_str(&emit_type(ret));
            }
            s.push('>');
            s
        }
        RustType::Named(name) => escape_ident(name),
        RustType::OpaquePtr { is_const } => {
            if *is_const {
                "*const core::ffi::c_void".into()
            } else {
                "*mut core::ffi::c_void".into()
            }
        }
        RustType::Unknown(desc) => format!("/* unknown: {} */ ()", desc),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_projection(items: Vec<RustItem>) -> RustProjection {
        RustProjection {
            items,
            ..Default::default()
        }
    }

    // 7.1: module/file layout
    #[test]
    fn emit_empty_projection() {
        let proj = RustProjection::new();
        let src = emit_source(&proj);
        assert!(src.contains("Generated by GERC"));
        assert!(src.contains("#![allow("));
    }

    #[test]
    fn emit_projection_notes_as_comments() {
        let mut proj = RustProjection::new();
        proj.notes.push(ProjectionNote {
            kind: NoteKind::Projected,
            message: "routine lowering".into(),
            item_name: Some("foo".into()),
        });
        proj.notes.push(ProjectionNote {
            kind: NoteKind::Provenance,
            message: "declared in demo.h:12".into(),
            item_name: Some("foo".into()),
        });
        proj.notes.push(ProjectionNote {
            kind: NoteKind::Partial,
            message: "layout evidence incomplete".into(),
            item_name: Some("bar".into()),
        });

        let src = emit_source(&proj);
        assert!(src.contains("// Projection notes:"));
        assert!(src.contains("// provenance [foo]: declared in demo.h:12"));
        assert!(src.contains("// partial [bar]: layout evidence incomplete"));
        assert!(!src.contains("routine lowering"));
    }

    // 7.2: extern "C" functions
    #[test]
    fn emit_function() {
        let proj = make_projection(vec![RustItem::Function(RustFunction {
            name: "foo".into(),
            parameters: vec![RustParameter {
                name: "x".into(),
                ty: RustType::CInt,
            }],
            return_type: RustType::CInt,
            variadic: false,
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("extern \"C\""));
        assert!(src.contains("pub fn foo(x: core::ffi::c_int) -> core::ffi::c_int;"));
    }

    #[test]
    fn emit_function_escapes_keyword_parameter_names() {
        let proj = make_projection(vec![RustItem::Function(RustFunction {
            name: "png_get_pCAL".into(),
            parameters: vec![RustParameter {
                name: "type".into(),
                ty: RustType::CInt,
            }],
            return_type: RustType::Void,
            variadic: false,
            doc: None,
        })]);

        let src = emit_source(&proj);
        assert!(src.contains("pub fn png_get_pCAL(r#type: core::ffi::c_int);"));
    }

    #[test]
    fn emit_missing_named_type_placeholders_before_aliases() {
        let proj = make_projection(vec![RustItem::TypeAlias(RustTypeAlias {
            name: "__gnuc_va_list".into(),
            target: RustType::Named("__builtin_va_list".into()),
            doc: None,
        })]);

        let src = emit_source(&proj);
        let placeholder = "#[repr(C)]\npub struct __builtin_va_list { _opaque: [u8; 0] }";
        let alias = "pub type __gnuc_va_list = __builtin_va_list;";
        assert!(src.contains(placeholder));
        assert!(src.contains(alias));
        assert!(src.find(placeholder).unwrap() < src.find(alias).unwrap());
    }

    #[test]
    fn emit_missing_named_type_placeholders_escape_rust_keywords() {
        let proj = make_projection(vec![RustItem::Function(RustFunction {
            name: "wire_handles".into(),
            parameters: vec![
                RustParameter {
                    name: "type".into(),
                    ty: RustType::Pointer {
                        pointee: Box::new(RustType::Named("type".into())),
                        is_const: false,
                    },
                },
                RustParameter {
                    name: "match".into(),
                    ty: RustType::Pointer {
                        pointee: Box::new(RustType::Named("match".into())),
                        is_const: true,
                    },
                },
            ],
            return_type: RustType::Named("Self".into()),
            variadic: false,
            doc: None,
        })]);

        let src = emit_source(&proj);
        assert!(src.contains("pub struct r#Self"));
        assert!(src.contains("pub struct r#match"));
        assert!(src.contains("pub struct r#type"));
        assert!(src.contains("r#type: *mut r#type"));
        assert!(src.contains("r#match: *const r#match"));
        assert!(src.contains("-> r#Self"));
    }

    #[test]
    fn emit_function_doc_comment() {
        let proj = make_projection(vec![RustItem::Function(RustFunction {
            name: "foo".into(),
            parameters: vec![],
            return_type: RustType::Void,
            variadic: false,
            doc: Some("Initialize foo".into()),
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("    /// Initialize foo"));
        assert!(src.contains("    pub fn foo();"));
    }

    #[test]
    fn emit_void_return_function() {
        let proj = make_projection(vec![RustItem::Function(RustFunction {
            name: "bar".into(),
            parameters: vec![],
            return_type: RustType::Void,
            variadic: false,
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("pub fn bar();"));
        assert!(!src.contains("->"));
    }

    #[test]
    fn emit_variadic_function() {
        let proj = make_projection(vec![RustItem::Function(RustFunction {
            name: "printf".into(),
            parameters: vec![RustParameter {
                name: "fmt".into(),
                ty: RustType::Pointer {
                    pointee: Box::new(RustType::CChar),
                    is_const: true,
                },
            }],
            return_type: RustType::CInt,
            variadic: true,
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(
            src.contains("pub fn printf(fmt: *const core::ffi::c_char, ...) -> core::ffi::c_int;")
        );
    }

    // 7.3: constants
    #[test]
    fn emit_constant() {
        let proj = make_projection(vec![RustItem::Constant(RustConstant {
            name: "API_VERSION".into(),
            ty: RustType::CInt,
            value: "3".into(),
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("pub const API_VERSION: core::ffi::c_int = 3;"));
    }

    #[test]
    fn emit_constant_doc_comment() {
        let proj = make_projection(vec![RustItem::Constant(RustConstant {
            name: "API_VERSION".into(),
            ty: RustType::CInt,
            value: "3".into(),
            doc: Some("API version constant".into()),
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("/// API version constant"));
        assert!(src.contains("pub const API_VERSION: core::ffi::c_int = 3;"));
    }

    // 7.4: struct
    #[test]
    fn emit_struct() {
        let proj = make_projection(vec![RustItem::Record(RustRecord {
            name: "Point".into(),
            kind: RustRecordKind::Struct,
            fields: vec![
                RustField {
                    name: "x".into(),
                    ty: RustType::CInt,
                },
                RustField {
                    name: "y".into(),
                    ty: RustType::CInt,
                },
            ],
            is_opaque: false,
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("#[repr(C)]"));
        assert!(src.contains("pub struct Point"));
        assert!(src.contains("pub x: core::ffi::c_int,"));
        assert!(src.contains("pub y: core::ffi::c_int,"));
    }

    #[test]
    fn emit_record_doc_comment() {
        let proj = make_projection(vec![RustItem::Record(RustRecord {
            name: "Point".into(),
            kind: RustRecordKind::Struct,
            fields: vec![],
            is_opaque: false,
            doc: Some("Cartesian point".into()),
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("/// Cartesian point"));
        assert!(src.contains("pub struct Point"));
    }

    // 7.5: union
    #[test]
    fn emit_union() {
        let proj = make_projection(vec![RustItem::Record(RustRecord {
            name: "Data".into(),
            kind: RustRecordKind::Union,
            fields: vec![
                RustField {
                    name: "i".into(),
                    ty: RustType::CInt,
                },
                RustField {
                    name: "f".into(),
                    ty: RustType::F32,
                },
            ],
            is_opaque: false,
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("pub union Data"));
    }

    // Opaque struct
    #[test]
    fn emit_opaque_struct() {
        let proj = make_projection(vec![RustItem::Record(RustRecord {
            name: "FILE".into(),
            kind: RustRecordKind::Struct,
            fields: vec![],
            is_opaque: true,
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("pub struct FILE { _opaque: [u8; 0] }"));
    }

    // 7.6: enum
    #[test]
    fn emit_enum() {
        let proj = make_projection(vec![RustItem::Enum(RustEnum {
            name: "Color".into(),
            variants: vec![
                RustEnumVariant {
                    name: "RED".into(),
                    value: Some(0),
                },
                RustEnumVariant {
                    name: "GREEN".into(),
                    value: Some(1),
                },
            ],
            repr: "i32".into(),
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("#[repr(i32)]"));
        assert!(src.contains("pub enum Color"));
        assert!(src.contains("RED = 0,"));
        assert!(src.contains("GREEN = 1,"));
    }

    #[test]
    fn emit_enum_doc_comment() {
        let proj = make_projection(vec![RustItem::Enum(RustEnum {
            name: "Color".into(),
            variants: vec![],
            repr: "i32".into(),
            doc: Some("Color enum".into()),
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("/// Color enum"));
        assert!(src.contains("pub enum Color"));
    }

    // 7.7: type alias
    #[test]
    fn emit_type_alias() {
        let proj = make_projection(vec![RustItem::TypeAlias(RustTypeAlias {
            name: "size_t".into(),
            target: RustType::CULong,
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("pub type size_t = core::ffi::c_ulong;"));
    }

    #[test]
    fn emit_type_alias_doc_comment() {
        let proj = make_projection(vec![RustItem::TypeAlias(RustTypeAlias {
            name: "size_t".into(),
            target: RustType::CULong,
            doc: Some("Platform size type".into()),
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("/// Platform size type"));
        assert!(src.contains("pub type size_t = core::ffi::c_ulong;"));
    }

    // 7.8: static
    #[test]
    fn emit_static() {
        let proj = make_projection(vec![RustItem::Static(RustStatic {
            name: "errno".into(),
            ty: RustType::CInt,
            mutable: true,
            doc: None,
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("pub static mut errno: core::ffi::c_int;"));
    }

    #[test]
    fn emit_static_doc_comment() {
        let proj = make_projection(vec![RustItem::Static(RustStatic {
            name: "errno".into(),
            ty: RustType::CInt,
            mutable: true,
            doc: Some("Thread-local error code".into()),
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("    /// Thread-local error code"));
        assert!(src.contains("    pub static mut errno: core::ffi::c_int;"));
    }

    // 7.9: deterministic ordering
    #[test]
    fn emit_deterministic_ordering() {
        let proj = make_projection(vec![
            RustItem::Constant(RustConstant {
                name: "A".into(),
                ty: RustType::CInt,
                value: "1".into(),
                doc: None,
            }),
            RustItem::TypeAlias(RustTypeAlias {
                name: "B".into(),
                target: RustType::CInt,
                doc: None,
            }),
            RustItem::Record(RustRecord {
                name: "C".into(),
                kind: RustRecordKind::Struct,
                fields: vec![],
                is_opaque: false,
                doc: None,
            }),
            RustItem::Function(RustFunction {
                name: "D".into(),
                parameters: vec![],
                return_type: RustType::Void,
                variadic: false,
                doc: None,
            }),
        ]);
        let src1 = emit_source(&proj);
        let src2 = emit_source(&proj);
        assert_eq!(src1, src2, "emission not deterministic");

        // Order: constants, type aliases, enums, records, extern block
        let pos_const = src1.find("pub const A").unwrap();
        let pos_alias = src1.find("pub type B").unwrap();
        let pos_struct = src1.find("pub struct C").unwrap();
        let pos_extern = src1.find("extern \"C\"").unwrap();
        assert!(pos_const < pos_alias);
        assert!(pos_alias < pos_struct);
        assert!(pos_struct < pos_extern);
    }

    // 7.10: golden-file-style test
    #[test]
    fn emit_full_surface() {
        let proj = make_projection(vec![
            RustItem::TypeAlias(RustTypeAlias {
                name: "size_t".into(),
                target: RustType::CULong,
                doc: None,
            }),
            RustItem::Enum(RustEnum {
                name: "status".into(),
                variants: vec![
                    RustEnumVariant {
                        name: "OK".into(),
                        value: Some(0),
                    },
                    RustEnumVariant {
                        name: "ERR".into(),
                        value: Some(1),
                    },
                ],
                repr: "i32".into(),
                doc: None,
            }),
            RustItem::Record(RustRecord {
                name: "Point".into(),
                kind: RustRecordKind::Struct,
                fields: vec![
                    RustField {
                        name: "x".into(),
                        ty: RustType::CInt,
                    },
                    RustField {
                        name: "y".into(),
                        ty: RustType::CInt,
                    },
                ],
                is_opaque: false,
                doc: None,
            }),
            RustItem::Function(RustFunction {
                name: "malloc".into(),
                parameters: vec![RustParameter {
                    name: "size".into(),
                    ty: RustType::Named("size_t".into()),
                }],
                return_type: RustType::OpaquePtr { is_const: false },
                variadic: false,
                doc: None,
            }),
            RustItem::Function(RustFunction {
                name: "free".into(),
                parameters: vec![RustParameter {
                    name: "ptr".into(),
                    ty: RustType::OpaquePtr { is_const: false },
                }],
                return_type: RustType::Void,
                variadic: false,
                doc: None,
            }),
            RustItem::Static(RustStatic {
                name: "errno".into(),
                ty: RustType::CInt,
                mutable: true,
                doc: None,
            }),
            RustItem::Constant(RustConstant {
                name: "VERSION".into(),
                ty: RustType::CInt,
                value: "42".into(),
                doc: None,
            }),
        ]);

        let src = emit_source(&proj);
        assert!(src.contains("pub type size_t = core::ffi::c_ulong;"));
        assert!(src.contains("pub enum status"));
        assert!(src.contains("pub struct Point"));
        assert!(src.contains("pub fn malloc(size: size_t) -> *mut core::ffi::c_void;"));
        assert!(src.contains("pub fn free(ptr: *mut core::ffi::c_void);"));
        assert!(src.contains("pub static mut errno: core::ffi::c_int;"));
        assert!(src.contains("pub const VERSION: core::ffi::c_int = 42;"));
    }

    // Emit type unit tests
    #[test]
    fn emit_type_void_ptr() {
        assert_eq!(
            emit_type(&RustType::OpaquePtr { is_const: false }),
            "*mut core::ffi::c_void"
        );
        assert_eq!(
            emit_type(&RustType::OpaquePtr { is_const: true }),
            "*const core::ffi::c_void"
        );
    }

    #[test]
    fn emit_type_fn_pointer() {
        let ty = RustType::FnPointer {
            params: vec![RustType::CInt],
            ret: Box::new(RustType::Void),
            variadic: false,
        };
        assert_eq!(
            emit_type(&ty),
            "Option<unsafe extern \"C\" fn(core::ffi::c_int)>"
        );
    }

    #[test]
    fn emit_type_array() {
        let ty = RustType::Array {
            element: Box::new(RustType::CInt),
            len: Some(10),
        };
        assert_eq!(emit_type(&ty), "[core::ffi::c_int; 10]");
    }

    #[test]
    fn emit_type_flexible_array() {
        let ty = RustType::Array {
            element: Box::new(RustType::CInt),
            len: None,
        };
        assert_eq!(emit_type(&ty), "[core::ffi::c_int; 0]");
    }

    #[test]
    fn emit_unsupported_item() {
        let proj = make_projection(vec![RustItem::Unsupported(RustUnsupported {
            name: Some("bad_thing".into()),
            reason: "bitfield".into(),
        })]);
        let src = emit_source(&proj);
        assert!(src.contains("// unsupported: bad_thing — bitfield"));
    }
}
